apiVersion: v1
kind: ConfigMap
metadata:
  name: event-platform-config
data:
  DB_URL: "jdbc:postgresql://postgresql:5432/event_platform"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_COUPON_PARTITIONS: "3"
  KAFKA_COUPON_CONSUMER_CONCURRENCY: "1"
  SPRING_PROFILES_ACTIVE: "local"
