apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-platform
  labels:
    app: event-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-platform
  template:
    metadata:
      labels:
        app: event-platform
    spec:
      containers:
        - name: event-platform
          image: event-platform:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: event-platform-config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 6
